"""add language to posts

Revision ID: 634dd2f3ac62
Revises: 89abf6695fec
Create Date: 2023-05-06 15:34:05.406569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634dd2f3ac62'
down_revision = '89abf6695fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
